name: Hourly Autobuild

on: 
  schedule:
    - cron: "0 * * * *"
  repository_dispatch:
    types: manual

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true
      - name: Commit changes
        shell: bash
        run: |
          LONG_HASH="$(git submodule status | grep -o [a-z0-9] | tr -d "\n")"
          SHORT_HASH="${LONG_HASH:0:7}"
          git config http.sslVerify false
          git config user.name "Automated Push"
          git config user.email "actions@users.noreply.github.com"
          git status
          git add -A
          git commit -m "Newsboat commit: ${SHORT_HASH}" || exit 0
      - name: Push changes
        shell: bash
        run: |
          REMOTE_REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${REMOTE_REPO}" HEAD:master
